from ensemblorg/ensembl-vep:release_101.0

MAINTAINER Seung Hoan Choi (schoi@broadinstitute.org)

RUN apt-get update sdf
RUN apt-get -y install git

RUN git clone https://github.com/konradjk/loftee.git
